### ISSUE TITLE
*** Skipped building workflows due to the error: Dependency "workflows" has no shared framework schemes

### ISSUE THREAD

**Issue by YSMooxx** [Carthage/workflows#13]
*** Skipped building workflows due to the error:
Dependency "workflows" has no shared framework schemes

**Comment by younata** [comment]
Are you sure you're filing this issue in the correct repository? https://github.com/Carthage/workflows (this one) is a collection of scripts for the Carthage tool and does not contain any code that should be built into a framework for your app. You should not include this repository in your Cartfile.

Closing this because there's no action on Carthage's part.
